In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# Display the first 5 rows
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [5]:
# Display rows and columns count
print(df.shape)

(891, 12)

In [6]:
# Get rows and columns separately
rows, columns = df.shape
print(f"Rows: {rows}, Columns: {columns}")

Rows: 891, Columns: 12

In [7]:
# Display data types of each column
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [8]:
# Drop the 'Cabin' column and save changes back to 'df'
df = df.drop(columns=['Cabin'])

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [10]:
# Calculate the mean age
mean_age = df['Age'].mean()

In [11]:
# Fill missing values in the 'Age' column with the mean age
df['Age'] = df['Age'].fillna(mean_age)

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [13]:
# Drop rows where 'Embarked' has missing values and reassign to df
df = df.dropna(subset=['Embarked'])
# Alternative using inplace=True:
# df.dropna(subset=['Embarked'], inplace=True)

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [15]:
# Calculate overall survival rate (as a decimal)
survival_rate = df['Survived'].mean()

In [16]:
# Convert to a percentage for easier reading
survival_percentage = survival_rate * 100
print(f"Overall Survival Rate: {survival_percentage:.2f}%")

Overall Survival Rate: 38.25%

In [17]:
# Calculate survival rates grouped by sex
survival_by_sex = df.groupby('Sex')['Survived'].mean()

# Display the results as percentages
for sex, rate in survival_by_sex.items():
    print(f"Survival rate for {sex}: {rate * 100:.2f}%")

Survival rate for female: 74.04%
Survival rate for male: 18.89%

In [18]:
# Calculate average age grouped by sex
average_age_by_sex = df.groupby('Sex')['Age'].mean()

# Display the results
for sex, avg_age in average_age_by_sex.items():
    print(f"Average age for {sex}: {avg_age:.1f} years")

Average age for female: 28.1 years
Average age for male: 30.5 years

In [19]:
# Calculate survival rates grouped by passenger class
survival_by_class = df.groupby('Pclass')['Survived'].mean()

# Display the results as percentages
for pclass, rate in survival_by_class.items():
    print(f"Survival rate for Class {pclass}: {rate * 100:.2f}%")

Survival rate for Class 1: 62.62%
Survival rate for Class 2: 47.28%
Survival rate for Class 3: 24.24%

In [20]:
# Calculate survival rates grouped by port of embarkation
survival_by_embarkation = df.groupby('Embarked')['Survived'].mean()

# Display the results as percentages
for port, rate in survival_by_embarkation.items():
    # C = Cherbourg, Q = Queenstown, S = Southampton
    print(f"Survival rate for Port {port}: {rate * 100:.2f}%")

Survival rate for Port C: 55.36%
Survival rate for Port Q: 38.96%
Survival rate for Port S: 33.70%

In [22]:
# Create a cross-tabulation table for raw counts of survivors
# Setting df['Survived'] == 1 filters for survivors only
survivors_df = df[df['Survived'] == 1]
ct_table = pd.crosstab(index=survivors_df['Pclass'], columns=survivors_df['Sex'])
print(ct_table)

Sex     female  male
Pclass
1           89    45
2           70    17
3           72    47

In [23]:
# 1. Recreate the cross-tabulation from the previous step
survivors_df = df[df['Survived'] == 1]
ct_table = pd.crosstab(index=survivors_df['Pclass'], columns=survivors_df['Sex'])

# 2. Stack the table
stacked_table = ct_table.stack()

print(stacked_table)

Pclass  Sex
1       female    89
        male      45
2       female    70
        male      17
3       female    72
        male      47
dtype: int64

In [24]:
# Assuming 'stacked_table' is the multi-indexed Series from the previous step
restored_table = stacked_table.unstack()

print(restored_table)

Sex     female  male
Pclass
1           89    45
2           70    17
3           72    47

In [25]:
# 1. Recreate your cross-tabulation and stack it
survivors_df = df[df['Survived'] == 1]
ct_table = pd.crosstab(index=survivors_df['Pclass'], columns=survivors_df['Sex'])
stacked_table = ct_table.stack()

# 2. Convert the stacked Series into a flat DataFrame so it can be merged
# 'name' gives a column title to the counted values
stacked_df = stacked_table.reset_index(name='Class_Sex_Survivor_Count')

# 3. Merge the original DataFrame with the flattened stacked table
# We match on 'Pclass' and 'Sex' to link the counts to the right rows
merged_df = df.merge(stacked_df, on=['Pclass', 'Sex'], how='left')

print(merged_df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Embarked  Class_Sex_Survivor_Count
0      0         A/5 21171   7.2500        S                        47
1      0          PC 17599  71.2833        C                        89
2      0  STON/O2. 3101282   7.9250        S                        72
3      0            113803  53.1000        S                        89
4      0            373450   8.0500        S                        47

In [26]:
# Calculate average age per class
avg_age_by_class = df.groupby('Pclass')['Age'].mean()
print("--- Average Age by Pclass ---")
print(avg_age_by_class)

--- Average Age by Pclass ---
Pclass
1    36.927073
2    29.866958
3    26.403259
Name: Age, dtype: float64

In [27]:
# Calculate min, max, and average survival rates per class
survival_stats = df.groupby('Pclass')['Survived'].agg(['min', 'max', 'mean'])

# Rename columns for clarity
survival_stats.columns = ['Min_Survived', 'Max_Survived', 'Survival_Rate']
print("\n--- Survival Stats by Pclass ---")
print(survival_stats)

--- Survival Stats by Pclass ---
        Min_Survived  Max_Survived  Survival_Rate
Pclass
1                  0             1       0.626168
2                  0             1       0.472826
3                  0             1       0.242363

In [28]:
# Filter for passengers older than 30
df_above_30 = df[df['Age'] > 30]

# Display the first few rows of the filtered dataset
print(df_above_30.head())

    PassengerId  Survived  Pclass  \
1             2         1       1
3             4         1       1
4             5         0       3
6             7         0       1
11           12         1       1

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
11                           Bonnell, Miss. Elizabeth  female  58.0      0

    Parch    Ticket     Fare Embarked
1       0  PC 17599  71.2833        C
3       0    113803  53.1000        S
4       0    373450   8.0500        S
6       0     17463  51.8625        S
11      0    113783  26.5500        S

In [34]:
data_df = pd.read_csv('data.csv')
for age in data_df['Age']:

        if age < 16 :

          data_df['person']= 'child' 

        if age > 16 :

          data_df['person'] = data_df['Sex']

print(data_df[:12])

    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3
11           12         1       1

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss. Laina  female  26.0      0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1
11                           Bonnell, Miss. Elizabeth  female  58.0      0

    Parch            Ticket     Fare Cabin Embarked  person
0       0         A/5 21171   7.2500   NaN        S    male
1       0          PC 17599  71.2833   C85        C  female
2       0  STON/O2. 3101282   7.9250   NaN        S  female
3       0            113803  53.1000  C123        S  female
4       0            373450   8.0500   NaN        S    male
5       0            330877   8.4583   NaN        Q    male
6       0             17463  51.8625   E46        S    male
7       1            349909  21.0750   NaN        S    male
8       2            347742  11.1333   NaN        S  female
9       0            237736  30.0708   NaN        C  female
10      1           PP 9549  16.7000    G6        S  female
11      0            113783  26.5500  C103        S  female

In [35]:
df = pd.read_csv("data.csv")

# Create a mapping dictionary
# (Note: In this specific case, the keys and values match perfectly, 
# which acts as a quick way to explicitly cast or clean the categories)
embarkation_map = {
    'S': 'S',
    'C': 'C',
    'Q': 'Q'
}

# Apply the mapping function back to the column
df['Embarked'] = df['Embarked'].map(embarkation_map)

print(df['Embarked'].value_counts())

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [36]:
# Use apply to measure character length of each name
df['Name_Length'] = df['Name'].apply(len)

# Display the first few rows to verify the new column
print(df[['Name', 'Name_Length']].head())

                                                Name  Name_Length
0                            Braund, Mr. Owen Harris           23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...           51
2                             Heikkinen, Miss. Laina           22
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)           44
4                           Allen, Mr. William Henry           24