In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read csv file
df = pd.read_csv('titanic.csv')

In [3]:
# Display first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
print(f"Number of rows: {len(df)}")
print(f"Number of columns: {len(df.columns)}")

Number of rows: 891
Number of columns: 12

In [5]:
# 1. Summary statistics for numerical columns
print("--- Numerical Summary Statistics ---")
print(df.describe())
print("\n")

--- Numerical Summary Statistics ---
       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [6]:
# 2. Summary statistics for categorical (text) columns
print("--- Categorical Summary Statistics ---")
print(df.describe(include='object'))

--- Categorical Summary Statistics ---
                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

C:\Users\Computer HuB\AppData\Local\Temp\ipykernel_9184\3600158617.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

In [7]:
# Identify columns with missing values 
print("--- Missing Values Per Column ---")
missing_counts = df.isnull().sum()
print(missing_counts)

--- Missing Values Per Column ---
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [8]:
# Filter to show only columns that actually have missing values
columns_with_missing = missing_counts[missing_counts > 0]
print(f"\nColumns containing missing data: {list(columns_with_missing.index)}\n")

Columns containing missing data: ['Age', 'Cabin', 'Embarked']

In [9]:
# Impute missing values in 'Age' with the Mean Age ---
# Calculate the mean age (Pandas automatically ignores NaN values when calculating the mean)
mean_age = df['Age'].mean()
print(f"Calculated Mean Age: {mean_age:.2f}")

Calculated Mean Age: 29.70

In [10]:
# Fill the missing values in the 'Age' column
df['Age'] = df['Age'].fillna(mean_age)
# Verify the Results 
print("\n--- Dataset After Imputation ---")
print(df)

print("\nRemaining missing values in 'Age':", df['Age'].isnull().sum())

--- Dataset After Imputation ---
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000
2                               Heikkinen, Miss. Laina  female  26.000000
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000
4                             Allen, Mr. William Henry    male  35.000000
..                                                 ...     ...        ...
886                              Montvila, Rev. Juozas    male  27.000000
887                       Graham, Miss. Margaret Edith  female  19.000000
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118
889                              Behr, Mr. Karl Howell    male  26.000000
890                                Dooley, Mr. Patrick    male  32.000000

     SibSp  Parch            Ticket     Fare Cabin Embarked
0        1      0         A/5 21171   7.2500   NaN        S
1        1      0          PC 17599  71.2833   C85        C
2        0      0  STON/O2. 3101282   7.9250   NaN        S
3        1      0            113803  53.1000  C123        S
4        0      0            373450   8.0500   NaN        S
..     ...    ...               ...      ...   ...      ...
886      0      0            211536  13.0000   NaN        S
887      0      0            112053  30.0000   B42        S
888      1      2        W./C. 6607  23.4500   NaN        S
889      0      0            111369  30.0000  C148        C
890      0      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

Remaining missing values in 'Age': 0

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
print("\nMissing values in 'Embarked':", df['Embarked'].isnull().sum())

Missing values in 'Embarked': 2

In [13]:
#Find the most frequent value (mode) 
# .mode() returns a Series, so we grab the first element [0]
most_frequent_embarked = df['Embarked'].mode()[0]
print(f"\nMost frequent 'Embarked' value: '{most_frequent_embarked}'")

Most frequent 'Embarked' value: 'S'

In [14]:
# Impute the missing values 
df['Embarked'] = df['Embarked'].fillna(most_frequent_embarked)
# Verify the Results 
print("\n--- After Imputation ---")
print(df)
print("\nMissing values in 'Embarked' now:", df['Embarked'].isnull().sum())

--- After Imputation ---
     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex        Age  \
0                              Braund, Mr. Owen Harris    male  22.000000
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000
2                               Heikkinen, Miss. Laina  female  26.000000
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000
4                             Allen, Mr. William Henry    male  35.000000
..                                                 ...     ...        ...
886                              Montvila, Rev. Juozas    male  27.000000
887                       Graham, Miss. Margaret Edith  female  19.000000
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118
889                              Behr, Mr. Karl Howell    male  26.000000
890                                Dooley, Mr. Patrick    male  32.000000

     SibSp  Parch            Ticket     Fare Cabin Embarked
0        1      0         A/5 21171   7.2500   NaN        S
1        1      0          PC 17599  71.2833   C85        C
2        0      0  STON/O2. 3101282   7.9250   NaN        S
3        1      0            113803  53.1000  C123        S
4        0      0            373450   8.0500   NaN        S
..     ...    ...               ...      ...   ...      ...
886      0      0            211536  13.0000   NaN        S
887      0      0            112053  30.0000   B42        S
888      1      2        W./C. 6607  23.4500   NaN        S
889      0      0            111369  30.0000  C148        C
890      0      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

Missing values in 'Embarked' now: 0

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
df['Sex'] = df['Sex'].map({'female': 0, 'male': 1})
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name  Sex        Age  SibSp  \
0                              Braund, Mr. Owen Harris    1  22.000000      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.000000      1
2                               Heikkinen, Miss. Laina    0  26.000000      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.000000      1
4                             Allen, Mr. William Henry    1  35.000000      0
..                                                 ...  ...        ...    ...
886                              Montvila, Rev. Juozas    1  27.000000      0
887                       Graham, Miss. Margaret Edith    0  19.000000      0
888           Johnston, Miss. Catherine Helen "Carrie"    0  29.699118      1
889                              Behr, Mr. Karl Howell    1  26.000000      0
890                                Dooley, Mr. Patrick    1  32.000000      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [17]:
numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch']

df[numeric_cols].describe()

              Age        Fare       SibSp       Parch
count  891.000000  891.000000  891.000000  891.000000
mean    29.699118   32.204208    0.523008    0.381594
std     13.002015   49.693429    1.102743    0.806057
min      0.420000    0.000000    0.000000    0.000000
25%     22.000000    7.910400    0.000000    0.000000
50%     29.699118   14.454200    0.000000    0.000000
75%     35.000000   31.000000    1.000000    0.000000
max     80.000000  512.329200    8.000000    6.000000

In [18]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    
    print(f"{col}: {len(outliers)} outliers")

Age: 66 outliers
Fare: 116 outliers
SibSp: 46 outliers
Parch: 213 outliers

In [19]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    df[col] = df[col].clip(lower=lower_bound, upper=upper_bound)

In [20]:
df[numeric_cols].describe()

              Age        Fare       SibSp  Parch
count  891.000000  891.000000  891.000000  891.0
mean    29.376817   24.046813    0.426487    0.0
std     12.062035   20.481625    0.708246    0.0
min      2.500000    0.000000    0.000000    0.0
25%     22.000000    7.910400    0.000000    0.0
50%     29.699118   14.454200    0.000000    0.0
75%     35.000000   31.000000    1.000000    0.0
max     54.500000   65.634400    2.500000    0.0

In [21]:
# Check duplicates
print("Number of duplicate rows:", df.duplicated().sum())

# Display duplicates
print(df[df.duplicated()])

# Remove duplicates
df = df.drop_duplicates()

# Verify
print("Number of duplicate rows after removal:", df.duplicated().sum())

Number of duplicate rows: 0
Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []
Number of duplicate rows after removal: 0

In [22]:
df['FamilySize'] = df['SibSp'] + df['Parch']

In [23]:
print(df[['SibSp', 'Parch', 'FamilySize']].head())

   SibSp  Parch  FamilySize
0    1.0      0         1.0
1    1.0      0         1.0
2    0.0      0         0.0
3    1.0      0         1.0
4    0.0      0         0.0

In [24]:
df['Title'] = df['Name'].str.extract(r',\s*([^.]*)\.')
print(df[['Name', 'Title']].head())

                                                Name Title
0                            Braund, Mr. Owen Harris    Mr
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   Mrs
2                             Heikkinen, Miss. Laina  Miss
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   Mrs
4                           Allen, Mr. William Henry    Mr

In [25]:
print(df['Title'].value_counts())

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [26]:
from sklearn.preprocessing import MinMaxScaler

numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch', 'FamilySize']

scaler = MinMaxScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

ModuleNotFoundError: No module named 'sklearn'

In [27]:
print(df[numeric_cols].head())

    Age     Fare  SibSp  Parch
0  22.0   7.2500    1.0      0
1  38.0  65.6344    1.0      0
2  26.0   7.9250    0.0      0
3  35.0  53.1000    1.0      0
4  35.0   8.0500    0.0      0

In [28]:
from sklearn.preprocessing import StandardScaler

numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch', 'FamilySize']

scaler = StandardScaler()

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

ModuleNotFoundError: No module named 'sklearn'

In [29]:
# 1. Check missing values
print("Missing values:")
print(df.isnull().sum())

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
FamilySize       0
Title            0
dtype: int64

In [30]:
# 2. Check duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [31]:
# 3. Check data types
print("\nData types:")
print(df.dtypes)

Data types:
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex              int64
Age            float64
SibSp          float64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
FamilySize     float64
Title              str
dtype: object

In [ ]:
# 4. Check number of rows and columns
print("\nDataset shape:", df.shape)

In [ ]:
# 5. Check unique values in categorical columns
print("\nSex values:")
print(df['Sex'].unique())

In [ ]:
print("\nEmbarked values:")
print(df[['Embarked_C', 'Embarked_Q', 'Embarked_S']].sum())

In [ ]:
# 6. Check numerical columns for invalid negative values
numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch', 'FamilySize']

In [ ]:
print("\nMinimum values:")
print(df[numeric_cols].min())

In [ ]:
# 7. Statistical summary
print("\nStatistical summary:")
print(df[numeric_cols].describe())